"""
Fluctuating/volatile discovery-universe tickers -- discovery layer.

NOT an index membership list and NOT a re-rank of the existing universe
(that's src/discovery/sources/volatility.py's job) -- this is a data-derived
screen for genuinely volatile names that fall OUTSIDE every other list:
too large for smallcap.py's $50M-$6B market-cap band (a recent IPO, a name
that's grown past $6B without an index seat yet) or simply not yet in
S&P 500/400/600. Built by scripts/build_volatile_universe.py -- see that
module's docstring for the full methodology: reuses smallcap.py's
existing-universe exclusion (so this never duplicates another list), then
screens what's left by Wilder's ATR(14) as a percentage of price (the same
metric src/discovery/sources/volatility.py re-ranks by) -- price > $0 and
90-day avg dollar volume > $0 (no real floor, only excludes bad-data/
never-traded names; originally >= $5 / >= $500,000/day, loosened 2026-08-24
at the user's explicit request -- see docs/ROADMAP.md Phase H), and
ATR% >= 2.0% (lowered same day from 3.0%).

Sourced 2026-08-24. Regenerate periodically with
`python -m scripts.build_volatile_universe` -- realized volatility drifts;
this is a snapshot, not a live feed.

Boundary: static reference data, no I/O, no live trading decision.
"""

from __future__ import annotations

SOURCED_DATE = "2026-08-24"

VOLATILE_TICKERS: list[str] = [
    "AADX", "AAOI", "AAUC", "ABCL", "ABEO", "ABSI", "ABUS", "ABVC", "ACCS", "ACHR",
    "ACHV", "ACON", "ACRS", "ACTU", "ACVA", "ACXP", "ADGM", "ADIL", "ADPT", "ADTN",
    "ADVB", "AEHR", "AEM", "AEMD", "AEON", "AEVA", "AFRM", "AGEN", "AGI", "AGIG",
    "AGIO", "AGL", "AI", "AIDX", "AIFA", "AIFF", "AIHS", "AIM", "AIMD", "AIOS",
    "AIP", "AIRE", "AIXC", "ALAB", "ALGS", "ALH", "ALKT", "ALLR", "ALM", "ALMR",
    "ALMS", "ALNT", "ALNY", "ALOY", "ALP", "ALZN", "AMBQ", "AMCX", "AMIX", "AMLX",
    "AMPL", "AMPX", "AMRC", "AMSC", "AMSS", "AMST", "AMZE", "ANAB", "ANDG", "ANNX",
    "ANRO", "ANY", "APEI", "APLD", "APPN", "APPS", "APRE", "APUS", "APVO", "AQB",
    "AQMS", "ARAI", "ARAY", "ARCO", "ARCT", "AREN", "ARHS", "ARIS", "ARQT", "ARTL",
    "ARTW", "ARX", "ARXS", "ASAN", "ASBP", "ASC", "ASM", "ASML", "ASR", "ASST",
    "ASTC", "ASTI", "ASTS", "ATCH", "ATCX", "ATEC", "ATER", "ATEX", "ATHR", "ATLC",
    "ATNM", "ATOS", "ATPC", "ATRC", "ATRO", "AUGO", "AUID", "AUPH", "AUR", "AUST",
    "AUUD", "AVAH", "AVAT", "AVBP", "AVEX", "AVO", "AVPT", "AVTX", "AVX", "AWRE",
    "AXGN", "AXIL", "AXS", "AXSM", "AXTI", "AYA", "AZIO", "AZTR", "B", "BAM",
    "BAND", "BAP", "BATRK", "BB", "BBAR", "BBGI", "BBIO", "BBLG", "BBNX", "BBSI",
    "BBUC", "BBW", "BCAB", "BCAX", "BCDA", "BCG", "BCH", "BCHT", "BCRX", "BCTX",
    "BE", "BEAM", "BEAT", "BEEM", "BELFA", "BENF", "BEPC", "BESS", "BETA", "BFLY",
    "BFRG", "BFRI", "BGDE", "BGI", "BHC", "BHST", "BHVN", "BIAF", "BIOA", "BIOT",
    "BIPC", "BIRD", "BIVI", "BJDX", "BKD", "BKSY", "BKV", "BKYI", "BLBD", "BLCO",
    "BLIN", "BLLN", "BLMN", "BLNE", "BLZE", "BMNR", "BN", "BNGO", "BNKK", "BOBS",
    "BODI", "BOLT", "BOXL", "BP", "BRAG", "BRBR", "BRFH", "BRLS", "BRLT", "BRTX",
    "BRUN", "BRZE", "BSAC", "BTAI", "BTG", "BTI", "BTLN", "BTMD", "BTOC", "BV",
    "BVN", "BVS", "BW", "BWIN", "BWMN", "BXC", "CABR", "CADL", "CAE", "CAI",
    "CALC", "CAPR", "CAPS", "CARE", "CBC", "CBL", "CBLL", "CBRS", "CCB", "CCC",
    "CCEL", "CCJ", "CDIO", "CDLX", "CDNA", "CDNL", "CDRE", "CDT", "CECO", "CELC",
    "CELZ", "CETX", "CETY", "CEVA", "CGAU", "CGEM", "CGON", "CHAI", "CHGA", "CHYM",
    "CIFR", "CIGI", "CIIT", "CISO", "CISS", "CJMB", "CLBK", "CLDI", "CLDX", "CLIR",
    "CLMT", "CLPS", "CLRB", "CLRO", "CLS", "CLYM", "CMCO", "CMCT", "CMND", "CMP",
    "CNET", "CNQ", "CNSY", "CNTX", "COAG", "COCP", "CODX", "COGT", "COHN", "COMP",
    "CORZ", "COSM", "COUR", "CPA", "CPHI", "CPNG", "CRAI", "CRCL", "CREX", "CRIS",
    "CRMT", "CRSP", "CRVO", "CRVS", "CRWS", "CRWV", "CSAI", "CSIQ", "CSQR", "CSTL",
    "CTOS", "CTRI", "CTRM", "CTSO", "CTXR", "CURX", "CVE", "CVKD", "CVM", "CWD",
    "CWH", "CX", "CXAI", "CYAB", "CYCN", "CYCU", "CYN", "CYRX", "DAIC", "DAIO",
    "DARE", "DBGI", "DC", "DCGO", "DCO", "DCOY", "DCTH", "DDS", "DEC", "DEO",
    "DETX", "DFLI", "DFNS", "DFSC", "DFTX", "DHT", "DJCO", "DJT", "DK", "DKNG",
    "DLO", "DNLI", "DNTH", "DOGZ", "DOO", "DRMA", "DRS", "DRVN", "DSGN", "DSGX",
    "DTST", "DUKR", "DUOT", "DXYZ", "DYAI", "DYN", "ECO", "ECVT", "EDBL", "EDSA",
    "EE", "EEIQ", "EFOI", "EFXT", "EHTH", "ELAB", "ELUT", "ELVN", "ELWT", "EMBJ",
    "ENSC", "ENVB", "EOLS", "EONR", "EQNR", "EQPT", "EQX", "ERAS", "ERNA", "ERO",
    "EROC", "ESLA", "ESQ", "ESTA", "ETON", "ETOR", "ETS", "EVC", "EVER", "EVLV",
    "EWTX", "EXYN", "EZRA", "FABC", "FBLG", "FCEL", "FCUV", "FDMT", "FEED", "FEIM",
    "FEMY", "FENC", "FET", "FF", "FFAI", "FGBI", "FGNX", "FHTX", "FIEE", "FIG",
    "FIGR", "FIGS", "FIP", "FIRY", "FISN", "FJET", "FLD", "FLGT", "FLL", "FLNA",
    "FLNC", "FLNT", "FLOC", "FLUX", "FLWS", "FLXS", "FLY", "FLYW", "FLYX", "FLZH",
    "FMST", "FMX", "FNGD", "FNGR", "FNKO", "FNRN", "FNUC", "FNV", "FOA", "FORR",
    "FOSL", "FPH", "FPS", "FRBT", "FRD", "FRHC", "FRMI", "FRMM", "FRNM", "FRSH",
    "FRTT", "FRVO", "FSK", "FSLY", "FSM", "FSP", "FSTR", "FSV", "FTAI", "FTCI",
    "FTEK", "FTFT", "FTH", "FTHM", "FTK", "FTLF", "FUBO", "FULC", "FURY", "FUSE",
    "FWDI", "FWONK", "FWRD", "FWRG", "GAIA", "GALT", "GAME", "GANX", "GASS", "GAU",
    "GBFH", "GCMG", "GCO", "GCTK", "GCTS", "GDRX", "GDYN", "GEMI", "GENB", "GENC",
    "GENK", "GEOS", "GERN", "GETY", "GEVO", "GFL", "GFR", "GFUZ", "GGB", "GH",
    "GHM", "GIB", "GIFT", "GIL", "GIPR", "GITS", "GLAS", "GLBS", "GLDG", "GLIBA",
    "GLIBK", "GLND", "GLNG", "GLOB", "GLOO", "GLSI", "GLUE", "GLXY", "GMRS", "GMTL",
    "GNLN", "GNLX", "GNPX", "GNSS", "GOAI", "GOGO", "GOLD", "GOOS", "GORO", "GOSS",
    "GOVX", "GP", "GPGI", "GPRE", "GPRK", "GPRO", "GRAL", "GRC", "GRCE", "GRDN",
    "GRDX", "GRI", "GRML", "GRND", "GRNQ", "GRNT", "GRO", "GROV", "GROY", "GRPN",
    "GRWG", "GSIT", "GSL", "GTBP", "GTE", "GTLB", "GTN", "GTX", "GUTS", "GVH",
    "GWAV", "GWH", "GWRS", "GXAI", "GYRE", "HAFN", "HAIN", "HAO", "HAPN", "HAWK",
    "HBB", "HBIO", "HCAT", "HCKT", "HCTI", "HCWB", "HCWC", "HDRN", "HDSN", "HEI",
    "HELE", "HELP", "HFFG", "HGBL", "HGTY", "HHH", "HHS", "HIFS", "HIHO", "HIPO",
    "HIT", "HITI", "HIVE", "HLF", "HLIO", "HLLY", "HLMN", "HMH", "HMR", "HMY",
    "HNGE", "HNRG", "HNST", "HODO", "HOFT", "HOV", "HOWL", "HPK", "HPP", "HQI",
    "HRI", "HROW", "HRTG", "HRTX", "HRZN", "HSCS", "HSDT", "HSHP", "HSLV", "HTCR",
    "HTFL", "HTZ", "HUBS", "HUMA", "HUN", "HURA", "HURN", "HUT", "HVT", "HWH",
    "HY", "HYFM", "HYFT", "HYLN", "HYMC", "HYPD", "HYPR", "IA", "IAUX", "IBEX",
    "IBIO", "IBRX", "IBTA", "ICCC", "ICFI", "ICU", "IDAI", "IDN", "IDR", "IDYA",
    "IE", "IFRX", "IFS", "IGC", "IHRT", "III", "IIIN", "IIIV", "IKT", "ILLR",
    "IMAX", "IMCC", "IMDX", "IMKTA", "IMMR", "IMMX", "IMNM", "IMNN", "IMPP", "IMRX",
    "IMSR", "IMUX", "IMVT", "IMXI", "INAB", "INBS", "INBX", "INDI", "INDP", "INFQ",
    "INFU", "INGM", "INGN", "INHD", "INM", "INMB", "INN", "INNV", "INO", "INOD",
    "INR", "INSE", "INSG", "INSM", "INTA", "INTG", "INTR", "INTS", "INTT", "INTZ",
    "INUV", "INV", "INVE", "IOND", "IONQ", "IONS", "IOT", "IOVA", "IPDN", "IPI",
    "IPSC", "IPST", "IPW", "IPWR", "IQST", "IRD", "IRIX", "IRMD", "IRON", "IRTC",
    "IRWD", "ISOU", "ISPC", "ISPR", "ITG", "ITP", "ITRG", "IVDA", "IVF", "IVVD",
    "IXHL", "IZEA", "JACK", "JAGU", "JAGX", "JAKK", "JAN", "JANX", "JBI", "JBIO",
    "JBS", "JCAP", "JCTC", "JELD", "JFB", "JILL", "JOB", "JOBY", "JRSH", "JRVR",
    "JSPR", "JTAI", "JUNS", "JYNT", "KALA", "KAPA", "KB", "KDK", "KE", "KEEL",
    "KELYA", "KEP", "KFRC", "KG", "KGC", "KGEI", "KIDS", "KINS", "KITT", "KLC",
    "KLRA", "KLRS", "KLTR", "KLXE", "KMTS", "KOD", "KODK", "KOPN", "KOS", "KPLT",
    "KPTI", "KRMD", "KRO", "KROS", "KRRO", "KRT", "KSCP", "KT", "KTTA", "KULR",
    "KURA", "KUST", "KVHI", "KVYO", "KWY", "KYIV", "KYMR", "KYTX", "LAB", "LABT",
    "LAC", "LAKE", "LAND", "LAR", "LASE", "LASR", "LAW", "LB", "LBRX", "LBTYA",
    "LCID", "LCLN", "LCTX", "LCUT", "LDI", "LE", "LEDS", "LEE", "LEGH", "LENZ",
    "LESL", "LEVI", "LEXX", "LFCR", "LFMD", "LFTO", "LFVN", "LGCY", "LGN", "LGO",
    "LGPS", "LGVN", "LHAI", "LIDR", "LIFE", "LILA", "LIME", "LIMN", "LINC", "LIND",
    "LINE", "LINK", "LION", "LIQT", "LITS", "LLYVA", "LLYVK", "LMB", "LMND", "LMRI",
    "LNAI", "LNG", "LNSR", "LNZA", "LOAR", "LOB", "LOCL", "LOCO", "LODE", "LOGI",
    "LOMA", "LONA", "LOOP", "LOVE", "LPCN", "LPLA", "LPSN", "LPTH", "LRHC", "LRMR",
    "LSAK", "LSF", "LSPD", "LSTA", "LTBR", "LTRN", "LTRX", "LUCD", "LUCK", "LUCY",
    "LUNG", "LUNR", "LVLU", "LVO", "LVWR", "LWAY", "LWLG", "LXEO", "LXRX", "LXU",
    "LYEL", "LYTS", "MAGN", "MAIA", "MAIR", "MAKO", "MANE", "MASS", "MATV", "MAX",
    "MAZE", "MBI", "MBIO", "MBLY", "MBOT", "MBRX", "MBUU", "MBX", "MCFT", "MCHB",
    "MCRB", "MCS", "MDA", "MDAI", "MDB", "MDCX", "MDGL", "MDLN", "MDXG", "MEC",
    "MED", "MEDS", "MELI", "MEOH", "MERC", "METC", "MFG", "MG", "MGA", "MGNI",
    "MGNX", "MGPI", "MGRX", "MGX", "MH", "MIAX", "MIND", "MINE", "MIRA", "MIRM",
    "MIST", "MITK", "MKZR", "MLAB", "MLCI", "MLSS", "MLYS", "MMED", "MNKD", "MNPR",
    "MNRO", "MNTK", "MNTN", "MNTS", "MOBI", "MOBX", "MOD", "MODD", "MOV", "MOVE",
    "MPAA", "MPLT", "MPTI", "MQ", "MRAM", "MRDN", "MRKR", "MRLN", "MRVI", "MSAI",
    "MSGE", "MSGM", "MSLE", "MSN", "MSS", "MSTR", "MT", "MTA", "MTC", "MTNB",
    "MTRX", "MTVA", "MTW", "MUFG", "MUX", "MVIS", "MVST", "MWH", "MWYN", "MX",
    "MXCT", "MYE", "MYGN", "MYO", "MYPS", "MYSE", "MYSZ", "NAGE", "NAK", "NAKA",
    "NAT", "NATR", "NAUT", "NAVN", "NB", "NBN", "NBR", "NBTX", "NCDL", "NCMI",
    "NCNO", "NCPL", "NCRA", "NDLS", "NDRA", "NEGG", "NEON", "NEOV", "NEPH", "NET",
    "NEUP", "NEXT", "NG", "NHP", "NHTC", "NIKI", "NIXX", "NKTR", "NMRK", "NMTC",
    "NN", "NNE", "NNVC", "NOMA", "NP", "NPKI", "NRDS", "NRIX", "NSPR", "NSYS",
    "NTGR", "NTLA", "NTR", "NTRA", "NTRP", "NTSK", "NTZ", "NUTX", "NUVB", "NUWE",
    "NVAX", "NVEC", "NVO", "NVTS", "NWPX", "NWTG", "NXE", "NXGL", "NXL", "NXPL",
    "NXTC", "NXTS", "NXXT", "NYC", "OBDC", "OCUL", "ODC", "OGC", "OKLO", "OLB",
    "OLMA", "OLOX", "OMDA", "OMER", "OMF", "ONCO", "ONDS", "ONFO", "ONMD", "ONT",
    "OPAD", "OPTH", "OPTT", "OR", "ORIC", "ORIO", "ORKA", "OSCR", "OSRH", "OTEX",
    "OTF", "OUST", "OWL", "PAAS", "PAC", "PACS", "PAGS", "PAM", "PAPL", "PAR",
    "PARA", "PASG", "PAVM", "PAX", "PAY", "PBK", "PBLS", "PBM", "PBR", "PCOR",
    "PCSA", "PCT", "PCVX", "PD", "PDS", "PDSB", "PETS", "PETZ", "PFAI", "PFSA",
    "PFSI", "PGEN", "PHAT", "PHGE", "PHIO", "PHR", "PHUN", "PIII", "PL", "PLAG",
    "PLAY", "PLGO", "PLOW", "PLPC", "PLSE", "PLUR", "PMCB", "PMI", "PNTG", "POCI",
    "POET", "POLA", "PPCB", "PPSI", "PPTA", "PRAX", "PRCH", "PRCT", "PRHI", "PRM",
    "PRMB", "PRPL", "PRSO", "PS", "PSIX", "PSNL", "PSQH", "PTN", "PTRN", "PUBM",
    "PUMP", "PURR", "PUSA", "PVLA", "PWCM", "PWP", "PWRL", "PXED", "PXLW", "PYXS",
    "PZG", "QBTS", "QCLS", "QGEN", "QMCO", "QMLS", "QNC", "QNCX", "QNME", "QNT",
    "QNTM", "QRHC", "QS", "QSI", "QSR", "QTI", "QTRX", "QUAD", "QUBT", "QUIK",
    "QXL", "QXO", "RAIL", "RAIN", "RANI", "RAPP", "RARE", "RBBN", "RBLX", "RBNE",
    "RBRK", "RC", "RCAT", "RCEL", "RCKT", "RCKY", "RCMT", "RDI", "RDVT", "RDW",
    "REA", "REAL", "REBN", "REED", "REFR", "REI", "REKR", "RELL", "RENT", "RENX",
    "REPL", "REPX", "RETO", "REVB", "RFIL", "RGNX", "RGP", "RGTI", "RHLD", "RICK",
    "RIG", "RIGL", "RILY", "RIME", "RIO", "RIOT", "RIVN", "RJET", "RKDA", "RKLB",
    "RKT", "RKTO", "RLAY", "RLGT", "RLMD", "RM", "RMAX", "RMCF", "RMCO", "RMIX",
    "RMNI", "RMTI", "RNA", "RNAC", "RNAZ", "RNGR", "RNTX", "RNXT", "ROC", "ROLR",
    "ROOT", "RPAY", "RPC", "RPD", "RPID", "RRGB", "RTB", "RUBI", "RUM", "RVLV",
    "RVMD", "RWAY", "RXRX", "RXST", "RXT", "RYAM", "RYOJ", "RYTM", "RYZ", "RZLT",
    "S", "SA", "SABS", "SAFX", "SAIL", "SAMG", "SAN", "SANA", "SAP", "SATL",
    "SB", "SBC", "SBET", "SBFM", "SBGI", "SBLK", "SBMT", "SBSW", "SCCO", "SCKT",
    "SCLX", "SCM", "SCNX", "SCOR", "SCTX", "SCWO", "SCYX", "SCZM", "SD", "SDEV",
    "SDHC", "SDOT", "SDRL", "SDST", "SEAT", "SEB", "SECZ", "SEER", "SEG", "SEGG",
    "SENEA", "SENS", "SEPN", "SER", "SERA", "SERV", "SES", "SFD", "SFIX", "SFL",
    "SG", "SGC", "SGHT", "SGLY", "SGML", "SGMT", "SGP", "SGRY", "SHAZ", "SHFS",
    "SHIM", "SHIP", "SHLS", "SHOE", "SHOP", "SI", "SIBN", "SID", "SIDU", "SIEB",
    "SIF", "SIGA", "SII", "SILO", "SIND", "SINT", "SION", "SITC", "SITE", "SKE",
    "SKIL", "SKIN", "SKM", "SKWD", "SKYA", "SKYE", "SKYH", "SKYQ", "SKYX", "SLDB",
    "SLDE", "SLDP", "SLE", "SLI", "SLND", "SLNG", "SLNH", "SLQT", "SLS", "SLSN",
    "SLSR", "SMC", "SMHI", "SMMT", "SMR", "SMRT", "SMTK", "SMXT", "SNAL", "SNAP",
    "SND", "SNDA", "SNDL", "SNDX", "SNES", "SNGX", "SNN", "SNOA", "SNOW", "SNTI",
    "SNWV", "SNYR", "SOAR", "SOBO", "SOBR", "SOC", "SOFI", "SONM", "SOTK", "SOUN",
    "SOWG", "SPAI", "SPB", "SPCE", "SPCX", "SPOK", "SPRB", "SPRO", "SPRU", "SPRY",
    "SPT", "SPTX", "SPWH", "SPWR", "SQM", "SRFM", "SRG", "SRI", "SRRK", "SRTA",
    "SRTS", "SRXH", "SRZN", "SSII", "SSMR", "SSNC", "SSP", "SSRM", "SST", "SSTI",
    "SSTK", "SSYS", "STDN", "STEM", "STEX", "STGW", "STI", "STIM", "STKE", "STKS",
    "STLA", "STM", "STN", "STNE", "STNG", "STOK", "STRO", "STRT", "STRZ", "STTK",
    "STUB", "STXS", "SU", "SUIG", "SUJA", "SUNB", "SUNE", "SURG", "SVCO", "SVM",
    "SVRA", "SVRN", "SVV", "SWAG", "SWBI", "SWIM", "SWMR", "SXC", "SXTP", "SYM",
    "SYPR", "SYRE", "TACT", "TANH", "TAOX", "TARA", "TARS", "TASK", "TAYD", "TBBB",
    "TBCH", "TBI", "TBN", "TCMD", "TCRT", "TCRX", "TCX", "TDAY", "TDOC", "TDUP",
    "TE", "TEAD", "TEAM", "TECX", "TELA", "TELO", "TEM", "TEN", "TENB", "TENX",
    "TEO", "TFII", "TFPM", "TFSL", "TG", "TGB", "TGEN", "TGL", "TGLS", "TGS",
    "TH", "THRY", "TIC", "TIGO", "TII", "TISI", "TITN", "TK", "TKC", "TKNO",
    "TLPH", "TLRY", "TLS", "TLSA", "TLSI", "TLYS", "TMC", "TMCI", "TMCR", "TMQ",
    "TMS", "TNET", "TNGX", "TNK", "TNON", "TNXP", "TNYA", "TOMZ", "TONX", "TOON",
    "TOPP", "TOPS", "TOVX", "TPB", "TPCS", "TPET", "TPG", "TPST", "TPVG", "TRAK",
    "TRAW", "TRDA", "TREE", "TRI", "TRLV", "TRMD", "TRNR", "TRNS", "TRON", "TRP",
    "TRS", "TRT", "TRUG", "TRVI", "TRX", "TSAT", "TSHA", "TSM", "TSQ", "TSSI",
    "TTAM", "TTAN", "TTEC", "TTGT", "TTI", "TTRX", "TUSK", "TV", "TVGN", "TVRD",
    "TVTX", "TW", "TWAV", "TWFG", "TWI", "TWIN", "TWST", "TXG", "TYGO", "TYRA",
    "TZOO", "U", "UAMY", "UAVS", "UEC", "UEIC", "UFI", "UI", "UIS", "ULBI",
    "ULCC", "ULH", "UMAC", "UMC", "UNCY", "UP", "UPB", "UPLD", "UPST", "UPXI",
    "URG", "UROY", "USAR", "USAS", "USAU", "USBC", "USDE", "USGO", "USIO", "USNA",
    "UUU", "UVE", "UWMC", "VANI", "VATE", "VBIO", "VBNK", "VEEA", "VEEE", "VELO",
    "VENU", "VERA", "VERI", "VERU", "VERX", "VET", "VFF", "VG", "VGAS", "VGZ",
    "VHC", "VHUB", "VIA", "VIDA", "VIP", "VISN", "VITL", "VIVK", "VIVS", "VKTX",
    "VMAR", "VMD", "VMET", "VNCE", "VNDA", "VNRX", "VOR", "VOXR", "VOYG", "VPG",
    "VRA", "VRCA", "VRDN", "VREX", "VRM", "VRNS", "VS", "VSTM", "VTAK", "VTEX",
    "VTGN", "VTIX", "VTS", "VTSI", "VTVT", "VUZI", "VVOS", "VWAV", "VYGR", "VZLA",
    "W", "WATT", "WBI", "WBTN", "WEAV", "WEST", "WETH", "WFG", "WGS", "WHK",
    "WHWK", "WIT", "WK", "WKHS", "WKSP", "WLDN", "WLFC", "WLTH", "WNC", "WOLF",
    "WOOF", "WPM", "WPRT", "WRAP", "WRN", "WTI", "WTTR", "WULF", "WVE", "WW",
    "WWR", "WYY", "XAIR", "XBIO", "XBP", "XCH", "XCUR", "XE", "XELB", "XENE",
    "XERS", "XFOR", "XGN", "XHLD", "XMAX", "XMTR", "XOS", "XP", "XPER", "XPOF",
    "XPON", "XRTX", "XRX", "XTIA", "XTNT", "XWEL", "XXI", "XZO", "YARW", "YCBD",
    "YEXT", "YHC", "YSS", "YSWY", "YUMC", "YYAI", "Z", "ZBIO", "ZENA", "ZEO",
    "ZETA", "ZG", "ZIP", "ZM", "ZNTL", "ZS", "ZSQR", "ZSTK", "ZTEK", "ZUMZ",
    "ZVIA", "ZVRA", "ZYME",
]
